### ISSUE TITLE
commons and noderesolve broken when used with mergeTrees

### ISSUE THREAD

**Issue by ohcibi** [chadhietala/broccoli-rollup#21]
Today I noticed that my project won't build anymore. The problem was that a commonjs module installed with npm couldn't be resolved anymore. The problem seemed to be some mismatch of subdependencies. So I've upgraded all my dependencies the problem still remained.

I then put together this little [test project](https://github.com/ohcibi/broccoli-rollup-test) which does nothing but imports 2 external dependencies and a local file with babel but uses (only to demonstrate) a `mergeTrees` result instead of a simple string. The project fails to build with this because it cannot resolve the node-resolve dependencies. Without `mergeTrees`, i.e. with `new Rollup("lib", .....)` instead the project builds properly and the built file contains the expected output.

**Comment by chadhietala** [comment]
It's likely that the external dependencies need to be part of the merged tree.

**Comment by ohcibi** [comment]
I cant try that right now in this example project but isn't that what node-resolve is for? It didn't helped in my real project where I've tried that already.

**Comment by ohcibi** [comment]
@chadhietala I just tried it and it didn't help. I'm not surprised by that because the project builds fine (including the source of the `import`'ed modules) without `mergeTrees` and as far as I understand broccoli-merge-trees `mergeTrees(["lib"])` and `"lib"` should be equivalent for a broccoli plugin.

**Comment by ohcibi** [comment]
@chadhietala in the meantime I have even verified that my real project builds properly (*without adding external dependencies to some mergeTree!!!*) when I pass a simple string to `new Rollup` as the first parameter instead of the result of `mergeTrees`. So this plugin is broken when it receives a broccoli node as a parameter.

**Comment by stefanpenner** [comment]
@ohcibi did you upgrade to broccoli v1.0.0 ?

**Comment by ohcibi** [comment]
@stefanpenner Why are you asking this? I provided a test case and put a link to its github repo into this issue. Heres what it says in the `package.json`

```
 "broccoli": "^1.1.1"
```

The test case here: https://github.com/ohcibi/broccoli-rollup-test is not my real project. Its a very small project that does nothing but demonstrate the reported issue with of course the latest dependencies by the time I created it. Please check it out before guessing.

**Comment by chadhietala** [comment]
I'm still trying to figure out what happened here. There is a breaking change in rollup between `0.37.0` and `0.37.1`.

**Comment by stefanpenner** [comment]
Rollup performing realpathSync on filepaths (mimicing nodes own behavior) seems to be causing this grief.

To address this, we need to dereference symlinks into a staging directory, in this directory we should then run rollup.

**Comment by chadhietala** [comment]
I think this can be closed now that #23 landed. Feel free to reopen if that is not the case.
