### ISSUE TITLE
Release 1.1.0 not semver compliant

### ISSUE THREAD

**Issue by mixonic** [chadhietala/broccoli-rollup#22]
https://github.com/ebryn/backburner.js/pull/186

Seems like the 1.1.0 release isn't a drop-in upgrade from 1.0.3. Backburner fails on `npm i`

<img width="1103" alt="screen shot 2017-02-17 at 7 53 22 pm" src="https://cloud.githubusercontent.com/assets/8752/23090144/64a3bf3c-f54b-11e6-973e-acc6762053b8.png">

**Comment by krisselden** [comment]
Are you sure this was the only dependency change? Something not being resolvable could be because of how node resolution interacts and can climb above the path. Maybe a change in merge trees?

**Comment by stefanpenner** [comment]
This is unrelated to this project, rather upstream package (rollup itself) now following symlinks is not semver.

**Comment by stefanpenner** [comment]
tracking the bug itself here: https://github.com/chadhietala/broccoli-rollup/issues/21
