### ISSUE TITLE
can't access the promise returned by rollup

### ISSUE THREAD

**Issue by fakalit** [chadhietala/broccoli-rollup#27]
since rollup executions happen asynchronously, I'm not sure how to handle its results inside a brocfile. is not being able to access promise returned by rollup the wanted behaviour in this case?

**Comment by stefanpenner** [comment]
can you provide an example of what you are trying to do?

**Comment by fakalit** [comment]
well, couple of things.

we have entry and destination files for each page in our application, so we have multiple rollup instances in our build process. I'm trying to notify the developer via a console log when each of them is completed, since the whole build takes lots of time. not being able to "then" the rollup instance makes things complicated here.

another thing is that we have tree shaking for stylesheets as well. 
but rollup plugin that handles css-modules and preprocessing (rollup-plugin-stylus-css-modules) does not produce broccoli node that we can funnel or merge. so idea is maybe we can make it output to a separate directory, which we later could funnel at the moment rolluping is completed. but that completion moment also not there since we can not access the promise returned by rollup.rollup()

also couple of little similar wants and needs.

**Comment by stefanpenner** [comment]
> we have entry and destination files for each page in our application, so we have multiple rollup instances in our build process. I'm trying to notify the developer via a console log when each of them is completed, since the whole build takes lots of time. not being able to "then" the rollup instance makes things complicated here.

You can use a general purpose broccoli helper for this:

https://github.com/stefanpenner/broccoli-stew/blob/master/lib/after-build.js#L5-L21

> but rollup plugin that handles css-modules and preprocessing (rollup-plugin-stylus-css-modules) does not produce broccoli node that we can funnel or merge. so idea is maybe we can make it output to a separate directory, which we later could funnel at the moment rolluping is completed.

Seems like a maybe a bug in that rollup plugin, if it doesn't write to an expected place? Can you provide a running example of this, i suspect that will be clearer.

**Comment by fakalit** [comment]
much thanks for the pointer for the stew. that really worked out nicely for logs. as for the running example, i'll try to isolate the case and share it.

I'm not sure if it's a bug. seems more like a design choice but could be an ugly one at that. 
since rollup is expected to return one big bundle, any other files on the side I think supposed to end up in unexpected places. that plugins writes that bundled up css file in somewhere in the file system that user specifies as a side effect, when its turn come up.  
as a result it operates besides broccoli's trees. even if our build fails and there is no "dist" folder, that css file it generated is still there. it's not part of the bundle.

I'm aware that these things maybe fall outside of the context of broccoli-rollup, but my thinking is since I can not "then" the new Rollup expression, I have no way to manipulate it before it returns the bundle as a tree. I'm not sure what could be the api design enabling that access, but it I figure it should help.

also, as far as I understand afterBuild helper in stew, could generate new side effects like console outputs. but is there a way to manipulate the passed tree and return it? 
in that case maybe we could do something like;
`views = stew.afterBuild(views, (views)=>{return merge([views, 'styles']); });`

**Comment by stefanpenner** [comment]
> also, as far as I understand afterBuild helper in stew, could generate new side effects like console outputs. but is there a way to manipulate the passed tree and return it?
> in that case maybe we could do something like;

there are other helpers stew provides that enable mutation.



> views = stew.afterBuild(views, (views)=>{return merge([views, 'styles']); });

This is unfortunately not valid, broccoli is 2 phase.

1. configuration (your brocfile, or ember-cli-build file)
2. build (what happens what your watcher runs, and the afterBuild callback invokes)

I suspect u just want to do

`view = merge([views, styles])` in your brocfile.js/ember-cli-build.js

**Comment by fakalit** [comment]
> I suspect u just want to do
> view = merge([views, styles]) in your brocfile.js/ember-cli-build.js

Yes, that's basically what I want to do. but at the moment of that merge there is no 'styles' directory in the file system. brocfile I have is basically like this:

```
let rolledUp = [];
for(let entry of pageEntries) {
  let roll = new Rollup(app, { rollup: {
    entry: `${entry}`,
    plugins: [ stylus({ output: `styles/${entry}/view.css` }) ]
  }});
  roll = stew.afterBuild(roll, ()=>{ log(`build: ${entry}`)) });
  rolledUp.push(roll);
}
log('1')
let views = merge(rolledUp);
views = merge([views, 'styles'])
log('2')
```
 it logs
`
1
2
build: a
build: b
build: c`

problem I have is 'new Rollup()' expression seems to works asynchronously and that is the reason I'm looking elsewhere like rollup's promise.

edit: oh ok, it is because it's 2 phase 😅
