### ISSUE TITLE
rollup-plugin-scss not working

### ISSUE THREAD

**Issue by afmeva** [chadhietala/broccoli-rollup#38]
I'm using the `rollup-plugin-scss` and it is not working. I dug a bit into the code and I found that the issue is related to 2 things:
  - The filter created with the rollup utils is returning false for the broccoli paths, and
  -  somehow, the writeFile method is being called but its callback is not. An empty file is being created.
 
PS. It is working using directly rollup.
my setup for broccoli
```
const sass = require('rollup-plugin-scss')
const Rollup = require('broccoli-rollup')
let js = new Rollup('app', {
  rollup: {
    input: 'app.js',
    output: {
      file: 'app.js',
      format: 'cjs'
    },
    plugins: [
      sass()
    ]
  }
})
````

my setup for rollup only

```
import sass from 'rollup-plugin-scss';

export default {
  input: 'app/app.js',
  output: {
    file: 'bundle.js',
    format: 'cjs',
  },
  plugins: [
    sass()
  ]
}
```

**Comment by krisselden** [comment]
plugins that use the onwrite hook to emit additional output currently do not work.

**Comment by krisselden** [comment]
onwrite hooks should work now, but I have not tried rollup-plugin-scss there maybe other issues with it
