### ISSUE TITLE
Error if processing a lib that has a node_modules directory

### ISSUE THREAD

**Issue by robmadole** [chadhietala/broccoli-rollup#39]
The following section:

https://github.com/chadhietala/broccoli-rollup/blob/74f8d074af14b02923c80c4070d884ce508fc3b9/index.ts#L82-L85

Creates the `node_modules` directory.

However if a library that this plugin is processing includes a `node_modules` directory already as part of the tree this fails:

https://github.com/chadhietala/broccoli-rollup/blob/74f8d074af14b02923c80c4070d884ce508fc3b9/index.ts#L94-L96

Is there a way to guard this?

**Comment by krisselden** [comment]
likely would be better to create a directory within the cache path that we build in and symlink the node_modules just above

**Comment by robmadole** [comment]
Thank you @krisselden. Appreciate your work on this project.
