### ISSUE TITLE
disable cycle warning by default

### ISSUE THREAD

**Issue by stefanpenner** [chadhietala/broccoli-rollup#46]
```
Circular dependency: ../../../../../var/folders/4r/whc65vwj1xggvvky3yy1cp9m000mw4/T/broccoli-67394EUBquvxT4wrc/cache-017-rollup_rsvp_js/build/rsvp/then.js -> ../../../../../var/folders/4r/whc65vwj1xggvvky3yy1cp9m000mw4/T/broccoli-67394EUBquvxT4wrc/cache-017-rollup_rsvp_js/build/rsvp/-internal.js -> ../../../../../var/folders/4r/whc65vwj1xggvvky3yy1cp9m000mw4/T/broccoli-67394EUBquvxT4wrc/cache-017-rollup_rsvp_js/build/rsvp/then.js
```

rollup doing this is just annoying, we can  likely do https://github.com/emberjs/data/pull/5839 here.

**Comment by krisselden** [comment]
I believe it warns because this causes issues with treeshaking.

**Comment by stefanpenner** [comment]
I’m not aware of tree shaking issues. I believe the warning exists, to warn against eager cycles not working, but lazy cycles working. Roll up is taking a more conversative stance then the es module spec.

Yes there are caveats with cycles, but it’s not clear rollup should warn if that cycle is intended and without caveat

**Comment by stefanpenner** [comment]
I can accept that a cycle is usually not needed and is a confusing/bad practice.

I’ll look st ember data’s cycle and see if they can just move stuff around

**Comment by rwjblue** [comment]
Ya, I definitely think the "right" thing is to silence the warning by actually removing the cycle. It should be possible in nearly every situation.

I'm going to close this one for now, as I don't think squelching a valid warning is a good practice for a general library.

**Comment by stefanpenner** [comment]
@rwjblue but valid and fully functional code which has no issues causes this warning.

**Comment by rwjblue** [comment]
Cycles _can_ work fine, but you can also easily end up in a situation where they don't. Rollup doesn't try to figure out if its going to be "ok", it just warns. 

_This_ library is a thin wrapper around Rollups behavior, if we want to change the default behavior to not warn (which probably requires a bit more internal wiring in Rollup itself, but I'm unsure) we should do that upstream in Rollup.
