### ISSUE TITLE
v4.1.0 should ignore watchedFiles that don't exist

### ISSUE THREAD

**Issue by krisselden** [chadhietala/broccoli-rollup#54]
So we check input files against rollupBuild.watchedFiles which is every resolved dependency (return value from `plugin.resolve(id, dep)`). Normally this is the absolute path to the dependency file but some plugins resolve ids that aren't real files. Typically these `id.startsWith('\0')` but rollup --watch just ignores watched files that error with `ENOENT` so likely we should just do the same.

**Comment by chadhietala** [comment]
fixed in #55
